In [6]:
import torch
import torch.nn as nn
import torch.nn.functional as F
import torch.optim as optim

In [7]:
 # 데이터 초기화
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[4], [5], [6]])

# 파라미터 초기화
W = torch.zeros(1, requires_grad=True)
b = torch.zeros(1, requires_grad=True)

In [8]:
# loss 함수 -> mse
loss_fn = nn.MSELoss()
# loss_fn = F.mse_loss()

# optimizer
optimizer = optim.SGD([W, b], lr=0.01)


In [9]:
epochs = 2000
for epoch in range(epochs + 1):

    obj_fn = x_train * W + b
    loss = loss_fn(obj_fn, y_train)

    # cost로 H(x) 개선
    optimizer.zero_grad()
    loss.backward()
    optimizer.step()

    # 100번마다 로그 출력
    if epoch % 100 == 0:
        print('Epoch {:4d}/{} W: {:.3f}, b: {:.3f} Cost: {:.6f}'.format(
            epoch, epochs, W.item(), b.item(), loss.item()
        ))

Epoch    0/2000 W: 0.213, b: 0.100 Cost: 25.666666
Epoch  100/2000 W: 1.740, b: 1.318 Cost: 0.407872
Epoch  200/2000 W: 1.582, b: 1.678 Cost: 0.252040
Epoch  300/2000 W: 1.457, b: 1.961 Cost: 0.155745
Epoch  400/2000 W: 1.359, b: 2.183 Cost: 0.096241
Epoch  500/2000 W: 1.283, b: 2.358 Cost: 0.059471
Epoch  600/2000 W: 1.222, b: 2.495 Cost: 0.036749
Epoch  700/2000 W: 1.175, b: 2.603 Cost: 0.022709
Epoch  800/2000 W: 1.137, b: 2.688 Cost: 0.014033
Epoch  900/2000 W: 1.108, b: 2.755 Cost: 0.008671
Epoch 1000/2000 W: 1.085, b: 2.807 Cost: 0.005358
Epoch 1100/2000 W: 1.067, b: 2.848 Cost: 0.003311
Epoch 1200/2000 W: 1.052, b: 2.881 Cost: 0.002046
Epoch 1300/2000 W: 1.041, b: 2.906 Cost: 0.001264
Epoch 1400/2000 W: 1.032, b: 2.926 Cost: 0.000781
Epoch 1500/2000 W: 1.025, b: 2.942 Cost: 0.000483
Epoch 1600/2000 W: 1.020, b: 2.955 Cost: 0.000298
Epoch 1700/2000 W: 1.016, b: 2.964 Cost: 0.000184
Epoch 1800/2000 W: 1.012, b: 2.972 Cost: 0.000114
Epoch 1900/2000 W: 1.010, b: 2.978 Cost: 0.000070

#### nn.Module로 구현

In [19]:
torch.manual_seed(1)

In [20]:
# 데이터
x_train = torch.FloatTensor([[1], [2], [3]])
y_train = torch.FloatTensor([[2], [4], [6]])

In [21]:
model = nn.Linear(1,1)
optimizer = torch.optim.SGD(model.parameters(), lr=0.01) 

In [22]:
nb_epochs = 2000
for epoch in range(nb_epochs+1):

    # H(x) 계산
    prediction = model(x_train)

    # cost 계산
    cost = F.mse_loss(prediction, y_train) # <== 파이토치에서 제공하는 평균 제곱 오차 함수

    # cost로 H(x) 개선하는 부분
    # gradient를 0으로 초기화
    optimizer.zero_grad()
    # 비용 함수를 미분하여 gradient 계산
    cost.backward() # backward 연산
    # W와 b를 업데이트
    optimizer.step()

    if epoch % 100 == 0:
    # 100번마다 로그 출력
      print('Epoch {:4d}/{} Cost: {:.6f}'.format(
          epoch, nb_epochs, cost.item()
      ))

Epoch    0/2000 Cost: 13.103541
Epoch  100/2000 Cost: 0.002791
Epoch  200/2000 Cost: 0.001724
Epoch  300/2000 Cost: 0.001066
Epoch  400/2000 Cost: 0.000658
Epoch  500/2000 Cost: 0.000407
Epoch  600/2000 Cost: 0.000251
Epoch  700/2000 Cost: 0.000155
Epoch  800/2000 Cost: 0.000096
Epoch  900/2000 Cost: 0.000059
Epoch 1000/2000 Cost: 0.000037
Epoch 1100/2000 Cost: 0.000023
Epoch 1200/2000 Cost: 0.000014
Epoch 1300/2000 Cost: 0.000009
Epoch 1400/2000 Cost: 0.000005
Epoch 1500/2000 Cost: 0.000003
Epoch 1600/2000 Cost: 0.000002
Epoch 1700/2000 Cost: 0.000001
Epoch 1800/2000 Cost: 0.000001
Epoch 1900/2000 Cost: 0.000000
Epoch 2000/2000 Cost: 0.000000


In [23]:
print(model(torch.FloatTensor([4.0])))

tensor([7.9989], grad_fn=<AddBackward0>)


In [24]:
print(list(model.parameters()))

[Parameter containing:
tensor([[1.9994]], requires_grad=True), Parameter containing:
tensor([0.0014], requires_grad=True)]
